### ISSUE TITLE
Kurze Info zu Sonderzeichen im Passwort 

### ISSUE THREAD

**Issue by dolorosus** [einstweilen/stv-catchall#2]
Eine kurze Info zu Sonderzeichen im Passwort wäre sinnvoll.
Es ist erforderlich, Sonderzeichen im Passwort url-encoded einzugeben (hat mich einige Zeit gekostet, bis ich drauf gekommen bin). 
Vielleicht ein Satz im Readme?

**Comment by dolorosus** [comment]
und nochwas:
paket_return=$(curl -s 'https://www.save.tv/STV/M/obj/user/JSON/userConfigApi.cfm?iFunction=7' -H 'Host: www.save.tv' -H 'User-Agent: Mozilla/5.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: de' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' --cookie "$stvcookie" -H 'Cache-Control: max-age=0' -H 'TE: Trailers')

liefert momentan leider kein Ergebnis. Rufe ich https://www.save.tv/STV/M/obj/user/JSON/userConfigApi.cfm?iFunction=7 im Browser auf, erhalte ich das erwartete Ergebnis:{"STRREGAINARTICLE":{"ID":33,"IPRICE":" 119,88€","SNAME":"Save.TV XL 12 Monate"}}

**Comment by einstweilen** [comment]
Nochmal Danke, das ist mir mit meinem ASCII Passwort gar nicht aufgefallen. 
Ich ergänze einen Hinweis und schau, ich das zeitnah gefixt bekomme.

**Comment by einstweilen** [comment]
Ich habe als Quickfix ein URLEncoding bei Stackoverflow https://stackoverflow.com/a/10797966 geborgt. Eigentlich hätte es auch mit einem direkten --data-urlencode beim cURL Loginaufruf gehen müssen, hat gerade nicht geklappt. Wichtig war mir, daß es schnell wieder funktioniert. 
Klappt es so bei Dir?

**Comment by dolorosus** [comment]
Logindaten in stv_autologin (PW url-encodiert) -> Script funktioniert
Keine Logindaten hinterlegt->Interaktive Abfrage, Logindaten gespeichert, ->Script funktioniert

**Comment by einstweilen** [comment]
Sehr gut, hatte es auf dem Mac & Pi getestet, aber seine eigenen Fehler sieht man ja immer nicht. 
Danke
